name: "npm should deploy"
description: "Checks to see if your package is semver higher than the latest prod version"
author: "Orta"
inputs:
  cwd:
    description: "The root of the package"
    default: "."
  npmTag:
    description: "The tag to use on npm for the check"
    default: "latest"

outputs:
  deploy:
    description: "Whether a deploy is needed"

runs:
  using: "node12"
  main: "dist/index.js"
